Feature process existing user invite emails
redacademy/potlucky-winter-2017 pull request #131
Opened 2017-03-24 23:12 UTC by justinl-y

Closes issue #87

2017-03-24 23:37 UTC, BlakeTurner requested changes
Code looks good, but you have to clean up the unused stuff

2017-03-24 23:37 UTC, BlakeTurner commented on js/components/InviteForm/index.js
> +    // console.log(decodeObjectValues(encodeObjectValues(data)));
!!!

2017-03-24 23:37 UTC, BlakeTurner commented on js/components/InviteForm/index.js
> +    console.log(encodedGuestEmails);
👊

2017-03-25 00:18 UTC, BlakeTurner commented
FYI Conflicts have arisen

2017-03-25 16:47 UTC, justinl-y commented on js/components/InviteForm/index.js
> +    // console.log(decodeObjectValues(encodeObjectValues(data)));
Done.

2017-03-25 16:47 UTC, justinl-y commented on js/components/InviteForm/index.js
> +    console.log(encodedGuestEmails);
Done.

2017-03-25 17:09 UTC, justinl-y commented
Conflicts and issues resolved.

2017-03-25 18:09 UTC, BlakeTurner approved these changes

2017-03-25 18:09 UTC, merged