built out styles
redacademy/potlucky-winter-2017 pull request #31
Opened 2017-03-13 23:00 UTC by jonathanfunk

Closes #7

2017-03-13 23:07 UTC, BlakeTurner requested changes
Good work.

Let's move `/js/assets` to just `/assets`

Also just one issue with a property in your styles.

2017-03-13 23:07 UTC, BlakeTurner commented on js/styles/baseStyles.js
> +  foodIndicatorNumb
This key is missing a value.

2017-03-13 23:17 UTC, BlakeTurner approved these changes

2017-03-13 23:33 UTC, scottfuoco commented on js/styles/baseStyles.js
> +  secondaryBtnColor: '#9DDA2C',
missing main or primaryBtnColor only have secondaryBtnColor

2017-03-13 23:33 UTC, scottfuoco commented on js/styles/baseStyles.js
> +  smallestSize: '10px',
Maybe add font to variable name ie. smallestFontSize

2017-03-13 23:33 UTC, scottfuoco commented on js/styles/baseStyles.js
> +    fontSize: headerSize,
this may break, did you mean typography.headerSize.  As well as putting object references for all variable lookups.

2017-03-14 16:25 UTC, ringong95 approved these changes

2017-03-14 16:29 UTC, merged