Feature overlay component
redacademy/potlucky-winter-2017 pull request #36
Opened 2017-03-14 22:12 UTC by scottfuoco

Added overlay component and fixed typography font families

2017-03-14 22:39 UTC, BlakeTurner requested changes

2017-03-14 22:39 UTC, BlakeTurner commented on js/components/Overlay/index.js
> +  </Text>
You've got `OrangeText` and `WhiteText` here which are basically identical. Do you think you'll have more? If you have 3 I'd recommend pulling the inner functionality into its own function.

2017-03-14 22:39 UTC, BlakeTurner commented on js/components/Overlay/styles.js
> +  }
Look for the repeats in here. `Dimensions.get('window').height` for example would be better off in its own variable.

2017-03-14 22:57 UTC, scottfuoco commented on js/components/Overlay/styles.js
> +  }
Totally agreed, I'll clean it up using the windowHeight and windowWidth variables from our baseStyles

2017-03-14 23:02 UTC, scottfuoco commented on js/components/Overlay/index.js
> +  </Text>
There will only be these two colours on the overlays, but I will make some modifications so that it isn't hard set to specific colours.

2017-03-15 16:08 UTC, BlakeTurner approved these changes

2017-03-15 16:08 UTC, merged