Styled bottom nav, icons.
redacademy/potlucky-winter-2017 pull request #46
Opened 2017-03-15 20:51 UTC by DjordjeVujatovic

2017-03-15 21:33 UTC, BlakeTurner requested changes

2017-03-15 21:33 UTC, BlakeTurner commented on js/navigation/NavigationLayout.ios.js
> +import { bottomNavigatorScreens, bottomNavigatorStyles } from './BottomNavConfig'
Nice work.

2017-03-15 21:33 UTC, BlakeTurner commented on js/scenes/AccountScreen/AccountScreenContainer.js
> +        <Image style={{height:30, width: 25}} source={require('../../../assets/images/accounticon.png')} />
Is there a reason this is the only one with a height of 30?

2017-03-15 21:33 UTC, BlakeTurner commented on js/navigation/BottomNavConfig.js
> +  }
Watch indentation at bottom of file

2017-03-15 21:33 UTC, BlakeTurner commented on js/scenes/AccountScreen/AccountScreenContainer.js
> +    tabBar:()=> ({
Cleaner spacing here:

```js
tabBar: () => ({

})
```

2017-03-15 21:33 UTC, BlakeTurner commented on js/scenes/CreatePotluckScreen/CreatePotluckScreenContainer.js
> +    tabBar:()=> ({
Spacing

2017-03-15 21:33 UTC, BlakeTurner commented on js/scenes/MyPotlucksScreen/MyPotlucksScreenContainer.js
> +    tabBar:()=> ({
Spacing

2017-03-15 22:41 UTC, DjordjeVujatovic commented on js/scenes/AccountScreen/AccountScreenContainer.js
> +        <Image style={{height:30, width: 25}} source={require('../../../assets/images/accounticon.png')} />
Just for sizing purposes, I changed it around a bit, but the width on this needs to stay at 25.

2017-03-16 03:44 UTC, BlakeTurner approved these changes

2017-03-16 03:44 UTC, merged