Feature progression bar
redacademy/potlucky-winter-2017 pull request #56
Opened 2017-03-17 17:25 UTC by scottfuoco

A bit of code clean up still required but pushing up so the screens associated with the progress bar can be connected.

2017-03-17 17:40 UTC, ringong95 approved these changes
Try to squash your commits next time but overall looks good.

2017-03-17 18:41 UTC, BlakeTurner requested changes

2017-03-17 18:41 UTC, BlakeTurner commented on js/components/CreatePotluckProgressBar/styles.js
> +const progressBarImageHeightWidthRatio = 59 / 702;
Where do these magic number come from?

2017-03-17 18:41 UTC, BlakeTurner commented on js/scenes/NumberOfGuestScreen/NumberOfGuestScreenContainer.js
> +    if (reg.test(text)) {
We're checking for numeric here, right? What if we just provided the numeric keyboard?

2017-03-17 18:41 UTC, BlakeTurner commented on js/scenes/PotLuckInfoScreen/PotluckInfoScreenContainer.js
> +      title: <CreatePotluckProgressBar title='Info' progressNumber={3} />,
3 is a magic number here. Is there somewhere we could store these as named constants and import them?

2017-03-17 20:33 UTC, scottfuoco commented on js/components/CreatePotluckProgressBar/styles.js
> +const progressBarImageHeightWidthRatio = 59 / 702;
They are the original image height and width, I can see if when we import the image it can be pulled off and stored.

2017-03-17 20:35 UTC, scottfuoco commented on js/scenes/NumberOfGuestScreen/NumberOfGuestScreenContainer.js
> +    if (reg.test(text)) {
We could change this to not allow .'s to be entered from the numeric keyboard so we dont get 2.3 values, or make sure the values are whole numbers .

2017-03-17 21:24 UTC, BlakeTurner commented on js/components/CreatePotluckProgressBar/styles.js
> +const progressBarImageHeightWidthRatio = 59 / 702;
Got it. Just give them names then.

2017-03-17 21:24 UTC, BlakeTurner commented on js/scenes/NumberOfGuestScreen/NumberOfGuestScreenContainer.js
> +    if (reg.test(text)) {
Right. Dirty solution. Fine for now

2017-03-17 22:58 UTC, BlakeTurner commented
Here be conflicts.

2017-03-20 17:21 UTC, BlakeTurner approved these changes

2017-03-20 17:21 UTC, merged