Feature number of guests styling
redacademy/potlucky-winter-2017 pull request #78
Opened 2017-03-22 01:35 UTC by scottfuoco

2017-03-22 16:11 UTC, BlakeTurner requested changes

2017-03-22 16:11 UTC, BlakeTurner commented on js/scenes/NumberOfGuestScreen/NumberOfGuestScreenContainer.js
> +  increase = () => this.setState({ count: (this.state.count * 1) + 1 });
Multiplying by 1?

2017-03-22 16:11 UTC, BlakeTurner commented on js/scenes/NumberOfGuestScreen/NumberOfGuestScreenContainer.js
> +      this.setState({ count: (this.state.count * 1) - 1 });
Same as above

2017-03-22 16:11 UTC, BlakeTurner commented on js/scenes/NumberOfGuestScreen/NumberOfGuestScreenContainer.js
> +    }
Put this logic in a function plz

2017-03-22 16:11 UTC, BlakeTurner commented on js/scenes/NumberOfGuestScreen/NumberOfGuestScreenContainer.js
> +    }
This should also be in its own function

2017-03-22 16:29 UTC, scottfuoco commented on js/scenes/NumberOfGuestScreen/NumberOfGuestScreenContainer.js
> +  increase = () => this.setState({ count: (this.state.count * 1) + 1 });
it's a quick way to convert the count from a string to an integer so that adding 1 doesnt result in string addition.

2017-03-22 16:46 UTC, scottfuoco commented on js/scenes/NumberOfGuestScreen/NumberOfGuestScreenContainer.js
> +  increase = () => this.setState({ count: (this.state.count * 1) + 1 });
i've changed it to use parseInt() now instead, not sure why * 1 was my goto solution for string to int

2017-03-22 20:22 UTC, BlakeTurner requested changes
Just the one tweak. When we give variables plural names it is implied that they are arrays.

2017-03-22 20:22 UTC, BlakeTurner commented on js/scenes/NumberOfGuestScreen/NumberOfGuestScreen.js
> +const NumberOfGuestScreen = ({ guestImageArr, count, onTextChange, increase, decrease }) => (
Instead of `guestImageArr`, name it `guestImages`

2017-03-23 16:26 UTC, BlakeTurner approved these changes

2017-03-23 16:26 UTC, merged